name = "TuningSystems"
uuid = "be38b862-5b2f-4079-a95f-952c4a32084e"
authors = ["Thomas Poulsen <ta.poulsen@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
